permalink: /:year/:month/:day/:title/
url: http://skyqinsc.github.io
author: Qinsc
highlighter: rouge 
exclude: ["Rakefile", "CNAME", "README.md"]
safe: true
paginate: 16


# markdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
