# Site settings
title: Algocode
email: skyqinsc@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Jekyll Theme Demo
baseurl: "/skyqinsc.github.io"       # the subpath of your site, e.g. /blog/
url: "http://skyqinsc.github.io"   # the base hostname & protocol for your site
twitter_username: username
github_username: skyqinsc

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
