# Site settings
title: Algocode
url: "http://skyqinsc.github.io"   # the base hostname & protocol for your site
github_username: skyqinsc
paginate: 100

highlighter: pygments

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
