markdown: rdiscount
permalink: /:title/
url: http://github.algocode.cn
#highlighter: pygments
pygments: true
name: Qbattle
description: Qbattle | Stop talking, start doing.
author: niushuai
email: skyqinsc@gmail.com
duoshuo: skyqinsc
weibo: 18627159396
safe: true
paginate: 100
about: "弱菜一枚。"
