markdown: rdiscount
permalink: /:title/
url: http://github.algocode.cn
pygments: true
name: Qbattle
description: Qbattle | Stop talking, start doing.
author: skyqinsc
email: skyqinsc@gmail.com
duoshuo: skyqinsc
weibo: 18627159396
hub: skyqinsc
safe: true
paginate: 100
about: "弱菜一枚。"
