permalink: /:year/:month/:day/:title/
url: https://skyqinsc.github.io
author: Qinsc
exclude: ["Rakefile", "CNAME", "README.md"]
safe: true
paginate: 16


# # markdown
# markdown: kramdown
# kramdown:
#   input: GFM                            # use Github Flavored Markdown !important

# highlighter: rouge

# basic setting
encoding: UTF-8
