permalink: /:year/:month/:day/:title/
url: https://skyqinsc.github.io
author: Qinsc
exclude: ["Rakefile", "CNAME", "README.md"]
safe: true
paginate: 16


# markdown
markdown: kramdown
# kramdown:
#   input: GFM
#   extensions:
#     - autolink
#     - footnotes
#     - smart
#   use_coderay: true
#   syntax_highlighter: rouge
#   coderay:
#     coderay_line_numbers:  nil

highlighter: rouge

# basic setting
encoding: UTF-8
